### ISSUE TITLE
ModuleNotFoundError: No module named 'pykeyboard'

### ISSUE THREAD

**Issue by nck974** [ActivityWatch/aw-watcher-input#6]
So I was continueing from #5, and then when I executed `poetry run aw-watcher-input` and I get:
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\myuser\activity_monitor\aw-watcher-input\src\aw_watcher_input\__init__.py", line 1, in <module>
    from . import main
  File "C:\Users\myuser\activity_monitor\aw-watcher-input\src\aw_watcher_input\main.py", line 9, in <module>
    from aw_watcher_afk.listeners import KeyboardListener, MouseListener
  File "C:\Users\myuser\AppData\Local\pypoetry\Cache\virtualenvs\aw-watcher-input-SuTwwcev-py3.9\lib\site-packages\aw_watcher_afk\listeners.py", line 6, in <module>
    from pykeyboard import PyKeyboardEvent
ModuleNotFoundError: No module named 'pykeyboard'
```
I tried installing `pip install pykeyboard`` but I think that has to be done somehow inside the virtual environment as It did not seem to work.

**Comment by ErikBjare** [comment]
The module missing is pyuserinput (which contains pykeyboard), you can try installing it in the venv with `poetry run pip install pyuserinput`.

It's not being installed since aw-watcher-afk doesn't require it on Windows (it uses another approach for AFK detection), but aw-watcher-input needs it on all platforms to function, so it should probably be added to the dependencies. I'll look into it.

**Comment by ErikBjare** [comment]
That's an issue with PyHook/PyWinHook which doesn't have any Python 3.9 compatible version on PyPI.

Try using Python 3.8 instead.

I also updated the pyproject.toml in https://github.com/ActivityWatch/aw-watcher-input/commit/3f88423e9edb5c585f5921711b8c665c63d1328e, so pyuserinput should now be installed correctly on `poetry install`.

**Comment by nck974** [comment]
@ErikBjare thank your for your help, unfortunately I think I can not further test the project, as I am not really familiar with handling multiple versions of python as I just installed my python with chocolatey and I need python 3.9 for other project.

I really appreaciate your time anyway.

**Comment by ErikBjare** [comment]
@nck974 That's okay. Thanks for being the first to test it out on Windows!

**Comment by ErikBjare** [comment]
The switch to pynput was completed in https://github.com/ActivityWatch/aw-watcher-input/commit/a232b68bb784ec2b6f8473b1cbd32c23431fe7f0. 

Should work on Windows now, but let me know if it doesn't!
